config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  root 'site/static_pages#home'
  
  devise_for :administrators
  
  get 'administrators/dashboard', as: 'administrator_root'

  match "/administrators/products/checked" => "administrators/products#checked", via: [:get, :post]


  scope module: 'site' do
    resources :products, only: [:show]

    resources :product_categories, only: [:show]

    resources :post_categories, only: [:show]

    resources :posts, only: [:show]

    resources :back_calls, only: [:create]

    resources :product_questions, only: [:create]

    resources :form_requests, only: [:create]

    resources :carts, only: [:show, :create, :destroy]

    resources :line_items, only: [:create, :destroy]
    
    resources :orders, only: [:create]
  end


  get "/contacts"          => "site/static_pages#contacts", via: [:get]
  get "/company_info"      => "site/static_pages#company_info", via: [:get]
  get "/delivery_info"     => "site/static_pages#delivery_info", via: [:get]
  get "/payment_info"      => "site/static_pages#payment_info", via: [:get]
  get "/terms_of_service"  => "site/static_pages#terms_of_service", via: [:get]

  get "/search_product"  => "site/static_pages#search_product", via: [:get]

  match "/orders/create_quick" => "site/orders#create_quick", via: [:post]


  namespace :administrators do
    resources :products, only: [:index, :edit, :update, :create, :destroy, :new]

    resources :product_attacments,  only: [:destroy]

    resources :product_categories, only: [:index, :edit, :update, :create, :destroy, :new]

    resources :post_categories, only: [:index, :edit, :update, :create, :destroy, :new]

    resources :posts, only: [:index, :edit, :update, :create, :destroy, :new]

    resources :menus, only: [:index, :edit]

    resources :menu_items, only: [:create, :update, :edit, :update] do
      get 'add_children', on: :member,  via: [:get]   
    end  

    resources :sliders, only: [:index, :edit]

    resources :slides, only: [:edit, :update, :create, :destroy, :new]

    resources :site_variables, only: [:edit, :update, :index]

    resources :pages, only: [:edit, :update, :index]

    resources :back_calls, only: [:index, :destroy]

    resources :product_questions, only: [:index, :show, :destroy]

    resources :banners, only: [:index, :edit, :update]

    resources :form_requests,  only: [:index, :show ,:destroy]

    resources :orders, only: [:index, :show, :destroy] 
  end


end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/product_question.rb
class ProductQuestion < ActiveRecord::Base

  belongs_to :product

	validates :phone, presence: true
	validates :text, presence: true
	validates :product_id, presence: true
  
end

app/controllers/administrators/back_calls_controller.rb
class Administrators::BackCallsController < AdministratorsController


  before_action :set_back_call, only: [:destroy]


  def index
    @back_calls = BackCall.all.paginate(:page => params[:page], :per_page => 20)
  end


  def destroy
    @back_call.destroy
    respond_to do |format|
      format.js {render js: "crud_ui.destroy_list_item(#{@back_call.id});"}
      format.html { redirect_to :back, notice: 'Заявка удалена' }
    end
  end


  private


  def set_back_call
    @back_call = BackCall.find(params[:id])
  end

end

app/controllers/administrators/banners_controller.rb
class Administrators::BannersController < AdministratorsController
  before_action :set_banner, only: [:edit, :destroy, :update]

  def edit
   
  end

  def index
  	@banners = Banner.all
  end



  def update
    @banner.update(banner_params)
    respond_to do |format|
      if @banner.save
        format.html { redirect_to :back, notice: 'Объект обновлен' }
      else
        format.html { redirect_to :back, notice: 'Произошла ошибка' }
      end
    end
  end


  private


  def set_banner
    @banner = Banner.find(params[:id])
  end

  def banner_params
    params.require(:banner).permit(:title, :image, :link)
  end
end

app/controllers/administrators/confirmations_controller.rb
class Administrators::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/administrators/form_requests_controller.rb
class Administrators::FormRequestsController < AdministratorsController


  before_action :set_form_request, only: [:show, :destroy]


  def index
    @form_requests = FormRequest.all.order('created_at DESC').paginate(:page => params[:page], :per_page => 20)
  end

  def show
    
  end

  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Объект удален' }
    end
  end


  private


  def set_form_request
    @request = FormRequest.find(params[:id])
  end

end

app/controllers/administrators/menu_items_controller.rb
class Administrators::MenuItemsController < AdministratorsController

  before_action :set_menu_item, only: [:edit, :update, :destroy]

  def edit
    @parent_items = @menu_item.menu.menu_items.where(ancestry: nil).order(:position)
    @children_items = @menu_item.children.order(:position)
    @parent_menu = @menu_item.menu
    
  end

  def update
    result = SAdministrator::SMenuItem::Update.new(@menu_item, params).main
    respond_to do |format|
      if result
        format.js {render js: "crud_ui.succes_update();"}
      else
        format.js {render js: "crud_ui.failed_update();"}
      end
    end
  end

  def new
    @menu_item = MenuItem.new()
    @menus  = Menu.all.collect{|item| [item.name, item.id ]}
  end

  def create
    result = SAdministrator::SMenuItem::Create.new(params).main
    respond_to do |format|
      if result
        format.html { redirect_to edit_administrators_menu_item_path(result), notice: 'Информация обновлена' }
      else
        format.html { redirect_to '/administrators/menus', notice: 'Произошла ошибка' }
      end
    end
  end

  def destroy
    @menu_item.destroy
    respond_to do |format|
      format.html { redirect_to edit_administrators_menu_path(@menu_item.menu_id), notice: 'Элемент удален' }
      format.js {render js: "crud_ui.destroy_list_item(#{@menu_item.id});"}
    end
  end


  def add_children
    @parent_menu_item = MenuItem.find(params[:id])
    @menu_item = MenuItem.new()
  end

  private

  def set_menu_item
    @menu_item = MenuItem.find(params[:id])
  end

end

app/controllers/administrators/menus_controller.rb
class Administrators::MenusController < AdministratorsController
  

  def index
    @menus = Menu.includes(:menu_items)
  end

  def edit
    @menu = Menu.find(params[:id])
    @menu_items = @menu.menu_items
    @parent_items = @menu_items.where(ancestry: nil).order(:position)

  end

end

app/controllers/administrators/omniauth_callbacks_controller.rb
class Administrators::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/administrators/orders_controller.rb
class Administrators::OrdersController < AdministratorsController

  before_action :set_order, only: [:show, :destroy]

  def index
    @orders = Order.all.order('created_at DESC').paginate(:page => params[:page], :per_page => 20)
  end

  def show

  end

  def destroy
    @order.destroy
    respond_to do |format|
      format.js {render js: "crud_ui.destroy_list_item(#{@order.id});"}
      format.html { redirect_to administrators_orders_path, notice: 'Заказ удален' }
    end
  end


  private


  def set_order
    @order = Order.find(params[:id])
  end

end

app/controllers/administrators/pages_controller.rb
class Administrators::PagesController < AdministratorsController


  before_action :set_page, only: [:edit, :update]


  def index
    @pages = Page.all
  end


  def update
    @page.update(page_params)
    respond_to do |format|
      if @page.save
        format.js {render js: "crud_ui.succes_update();"}
      else
        format.js {render js: "crud_ui.failed_update();"}
      end
    end
  end

  def edit

  end



  private


  def set_page
    @page = Page.find(params[:id])
  end

  def page_params
    params.require(:page).permit(:name, :description, :meta_title, :meta_description, :meta_keywords)
  end


end

app/controllers/administrators/passwords_controller.rb
class Administrators::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/administrators/post_categories_controller.rb
class Administrators::PostCategoriesController < AdministratorsController


  before_action :set_post_category, only: [:edit, :update, :destroy]


  def index
    @post_categories = PostCategory.includes(:post_category).order('created_at DESC').paginate(:page => params[:page], :per_page => 20)
  end

  def new
    @post_category = PostCategory.new()
    @list_to_form = PostCategory.all.collect{|category| [category.name, category.id]} << ['Родитель', 0]
  end

  def create
    @post_category = PostCategory.new(post_category_params)
    respond_to do |format|
      if @post_category.save
        format.html { redirect_to edit_administrators_post_category_path(@post_category), notice: 'Информация сохранена' }
      else
       format.js {render js: "crud_ui.failed_update();"}
        format.html { redirect_to :back, notice: 'Произошла ошибка' }
      end
    end
  end

  def update
    @post_category.update(post_category_params)
    respond_to do |format|
      if @post_category.save
        format.html { redirect_to edit_administrators_post_category_path(@post_category), notice: 'Информация сохранена' }
      else
        format.html { redirect_to edit_administrators_post_category_path(@post_category), notice: 'Произошла ошибка' }
      end
    end
  end

  def edit
    @list_to_form = PostCategory.all.collect{|category| [category.name, category.id]} << ['Родитель', 0]
  end

  def destroy
    @post_category.destroy
    respond_to do |format|
      format.js {render js: "crud_ui.destroy_list_item(#{@post_category.id});"}
      format.html { redirect_to administrators_post_categories_path, notice: 'Категория удалена' }
    end
  end


  private


  def set_post_category
    @post_category = PostCategory.friendly.find(params[:id])
  end

  def post_category_params
    params.require(:post_category).permit(:name, :post_category_id, :slug, :description, :meta_title,
                                          :meta_description, :meta_keywords, :avatar)
  end


end

app/controllers/administrators/posts_controller.rb
class Administrators::PostsController < AdministratorsController


  before_action :set_post_category, only: [:edit, :update, :destroy]


  def index
    @posts = Post.includes(:post_category).order('created_at DESC').paginate(:page => params[:page], :per_page => 20)
  end

  def new
    @post = Post.new()
    @access_categores = PostCategory.all.collect{|category| [category.name, category.id]} << ['Без категории', 0]
  end

  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to edit_administrators_post_path(@post), notice: 'Запись сохранена' }
      else
        format.html { redirect_to :back, notice: 'Произошла ошибка' }
      end
    end
  end

  def update
    @post.update(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to edit_administrators_post_path(@post), notice: 'Информация сохранена' }
      else
        format.html { redirect_to edit_administrators_post_path(@post), notice: 'Произошла ошибка' }
      end
    end
  end

  def edit
    @access_categores = PostCategory.all.collect{|category| [category.name, category.id]} << ['Без категории', 0]
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.js {render js: "crud_ui.destroy_list_item(#{@post.id});"}
      format.html { redirect_to administrators_posts_path, notice: 'Запись удалена' }
    end
  end


  private


  def set_post_category
    @post = Post.friendly.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:name, :post_category_id, :slug, :content, :avatar,
                                 :meta_title, :meta_description, :meta_keywords, :lead)
  end


end

app/controllers/administrators/product_attacments_controller.rb
class Administrators::ProductAttacmentsController < AdministratorsController

  def destroy
    attacment = ProductAttachment.find(params[:id])
    attacment.destroy
    respond_to do |format|
      format.js {render js: "crud_ui.destroy_list_item(#{attacment.id});"}
    end
  end
 

end

app/controllers/administrators/product_categories_controller.rb
class Administrators::ProductCategoriesController < AdministratorsController


  before_action :set_product_category, only: [:edit, :update, :destroy]


  def index
    @product_categories = ProductCategory.includes(:product_category).order(:name).paginate(:page => params[:page], :per_page => 20)
  end

  def new
    @product_category = ProductCategory.new()
    @list_to_form     = ProductCategory.all.collect{|category| [category.name, category.id]} << ['Родитель', 0]
  end

  def create
    @product_category = ProductCategory.new(product_category_params)
    respond_to do |format|
      if @product_category.save
        format.html { redirect_to edit_administrators_product_category_path(@product_category), notice: 'Информация сохранена' }
      else
        format.html { redirect_to :back, notice: 'Произошла ошибка' }
      end
    end
  end

  def update
    @product_category.update(product_category_params)
    respond_to do |format|
      if @product_category.save
        format.html { redirect_to edit_administrators_product_category_path(@product_category), notice: 'Информация сохранена' }
      else
        format.html { redirect_to edit_administrators_product_category_path(@product_category), notice: 'Произошла ошибка' }
      end
    end
  end

  def edit
    @list_to_form = ProductCategory.all.collect{|category| [category.name, category.id]} << ['Родитель', 0]
  end

  def destroy
    @product_category.destroy
    respond_to do |format|
      format.html { redirect_to administrators_product_categories_path, notice: 'Категория удалена' }
      format.js {render js: "crud_ui.destroy_list_item(#{@product_category.id});"}
    end
  end


  private


  def set_product_category
    @product_category = ProductCategory.friendly.find(params[:id])
  end

  def product_category_params
    params.require(:product_category).permit(:name, :product_category_id, :slug, :description, :meta_title,
                                          :meta_description, :meta_keywords, :avatar, :large_avatar)
  end


end

app/controllers/administrators/product_questions_controller.rb
class Administrators::ProductQuestionsController < AdministratorsController


  before_action :set_product_question, only: [:show, :destroy]


  def index
    @product_questions = ProductQuestion.all.includes(:product).order('created_at DESC').paginate(:page => params[:page], :per_page => 20)
  end

  def show
 
  end

  def destroy
    @product_question.destroy
    respond_to do |format|
      format.js {render js: "crud_ui.destroy_list_item(#{@product_question.id});"}
      format.html { redirect_to :back, notice: 'Вопрос удален' }
    end
  end


  private


  def set_product_question
    @product_question = ProductQuestion.find(params[:id])
  end

end

app/controllers/administrators/service_controller.rb
class Administrators::ServiceController < AdministratorsController

  #загрузить демо данные
  def load_demo_data
    
  end

  #удалить демо данные
  def remove_demo_data
    
  end

end

app/views/administrators/product_questions/index.html.erb
<div id="page_content_inner">
    <h3 class="heading_b uk-margin-bottom">Вопросы по товарам</h3>
    <% if @product_questions.size == 0 %>
    <div class="md-card">
        <div class="md-card-content">
            <div class="uk-grid" data-uk-grid-margin>
                <div class="uk-width-1-1">
                <center> Отсутствуют элементы для отображения </center></div>
            </div>
        </div>
    </div>
    <% else %>
    <div class="uk-grid uk-grid-medium" data-uk-grid-margin>
        <div class="uk-width-xLarge-10-10  uk-width-large-10-10">
            <div class="md-card">
                <div class="md-card-content">
                    <div class="uk-overflow-container uk-margin-bottom">
                        <table class="uk-table uk-table-nowrap uk-table-hover" id="ts_pager_filter">
                            <thead>
                                <tr>
                                    <th class="uk-text-center">id</th>
                                    <th class="uk-text-center">Артикул товара</th>
                                    <th class="uk-text-center">Название товара</th>
                                    <th class="uk-text-center">Имя</th>
                                    <th class="uk-text-center">Телефон</th>
                                    <th class="uk-text-center">Дата создания</th>
                                    <th class="uk-text-center">Действия</th>
                                </tr>
                            </thead>
                            <tbody>
                                <% @product_questions.each do |question| %>
                                <tr class="item<%= question.id %>">
                                    <td class="uk-text-center"><%= question.id %></td>
                                    <td class="uk-text-center"><%= question.product.id %></td>
                                    <td class="uk-text-center"><%= question.product.name %></td>
                                    <td class="uk-text-center"><%= question.name %></td>
                                    <td class="uk-text-center"><%= question.phone %></td>
                                    <td class="uk-text-center"><%= question.created_at %></td>
                                    
                                    <td class="uk-text-center">
                                        <%= link_to "<i class=\"material-icons md-24\">&#xE88F;</i>".html_safe, administrators_product_question_path(question) %>
                                        <%= link_to "<i class=\"material-icons md-24\">&#xE872;</i>".html_safe, administrators_product_question_path(question), method: :delete, remote: true, data: {confirm: "Удалить запись? "} %>
                                    </td>
                                </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                    <div class="will_paginate_plugin uk-text-center">
                        <%= will_paginate @product_questions %>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
    <% end %>
</div>

app/views/administrators/product_questions/show.html.erb
<div id="page_heading">
    <h1 id="product_edit_name">Вопрос № <%= @product_question.id %></h1>
    <span class="uk-text-muted uk-text-upper uk-text-small" id="product_edit_sn">Дата создания: <%= @product_question.created_at %></span>
</div>
<div id="page_content_inner">
    <div class="uk-grid uk-grid-medium" data-uk-grid-margin>
        <div class="uk-width-xLarge-10-10  uk-width-large-10-10">
            <h3 class="heading_b uk-margin-bottom">Контакты клиента</h3>
            <div class="md-card">
                <div class="md-card-content">
                    <div class="uk-overflow-container uk-margin-bottom">
                          <p><span class="uk-text-bold">Имя: </span> <%= @product_question.name %></p>
                          <p><span class="uk-text-bold">Телефон: </span> <%= @product_question.phone %></p>
                          <p><span class="uk-text-bold">Текст вопроса: </span> <%= @product_question.text %></p>            
                    </div>
                </div>
            </div>
            <br />

            <h3 class="heading_b uk-margin-bottom">Товар</h3>
            <div class="md-card">
                <div class="md-card-content">
                    <div class="uk-overflow-container uk-margin-bottom">
                          <p><span class="uk-text-bold">Имя: </span> <%= link_to @product_question.product.name, product_path(@product_question.product) %></p>
                          <p><span class="uk-text-bold">Цена: </span> <%= @product_question.product.price %> р.</p>
                          <p><span class="uk-text-bold">Категория: </span> <%= @product_question.product.product_category.name if @product_question.product.product_category %></p>            
                    </div>
                </div>
            </div>
            
            
        </div>
    </div>
    <div class="md-fab-wrapper">
        <a class="md-btn" href="/administrators/product_questions/">Назад</a>
        <%= link_to "Удалить".html_safe, administrators_product_question_path(@product_question), method: :delete, class: "md-btn md-btn-danger" %>
    </div>
</div>